"""
Bench Export: Save benchmark results as JSON, CSV, or HTML.

Usage:
    from aip_bench.export import to_json, to_csv, to_html

    to_json(result, "results.json")
    to_csv(result, "results.csv")
    to_html(report, "report.html")

Author: Carmen Esteban
"""

import csv
import io
import json
from pathlib import Path


def to_json(result, path=None, indent=2):
    """Export BenchmarkResult or ComparisonReport to JSON.

    Parameters
    ----------
    result : BenchmarkResult or ComparisonReport
        Result to export.
    path : str or Path, optional
        Output file. If None, returns string.
    indent : int
        JSON indentation.

    Returns
    -------
    str or None
        JSON string if path is None.
    """
    data = result.to_dict() if hasattr(result, "to_dict") else result
    text = json.dumps(data, indent=indent, default=str)
    if path:
        Path(path).write_text(text)
        return None
    return text


def to_csv(result, path=None):
    """Export BenchmarkResult or ComparisonReport to CSV.

    Parameters
    ----------
    result : BenchmarkResult or ComparisonReport
        Result to export.
    path : str or Path, optional
        Output file. If None, returns string.

    Returns
    -------
    str or None
        CSV string if path is None.
    """
    output = io.StringIO()
    writer = csv.writer(output)

    if hasattr(result, "results"):
        # ComparisonReport
        writer.writerow(["config", "benchmark", "metric", "value"])
        for cfg, benchmarks in result.results.items():
            for bench_name, br in benchmarks.items():
                for metric, value in br.metrics.items():
                    writer.writerow([cfg, bench_name, metric, value])
    else:
        # Single BenchmarkResult
        d = result.to_dict() if hasattr(result, "to_dict") else result
        writer.writerow(["benchmark", "metric", "value"])
        for metric, value in d.get("metrics", {}).items():
            writer.writerow([d.get("name", ""), metric, value])

    text = output.getvalue()
    if path:
        Path(path).write_text(text)
        return None
    return text


def to_html(result, path=None, title="AIP Bench Results"):
    """Export BenchmarkResult or ComparisonReport to HTML.

    Parameters
    ----------
    result : BenchmarkResult or ComparisonReport
        Result to export.
    path : str or Path, optional
        Output file. If None, returns string.
    title : str
        Page title.

    Returns
    -------
    str or None
        HTML string if path is None.
    """
    parts = [
        "<!DOCTYPE html>",
        "<html><head>",
        f"<title>{_esc(title)}</title>",
        "<style>",
        "body{font-family:system-ui,sans-serif;max-width:960px;"
        "margin:2em auto;padding:0 1em}",
        "h1{color:#1a1a2e}",
        "h2{color:#16213e;border-bottom:2px solid #0f3460;"
        "padding-bottom:.3em}",
        "table{border-collapse:collapse;width:100%;margin:1em 0}",
        "th,td{border:1px solid #ddd;padding:8px 12px;text-align:left}",
        "th{background:#0f3460;color:#fff}",
        "tr:nth-child(even){background:#f2f2f2}",
        "tr:hover{background:#e0e7ff}",
        ".meta{color:#6b7280;font-size:.9em}",
        "</style>",
        "</head><body>",
        f"<h1>{_esc(title)}</h1>",
    ]

    if hasattr(result, "results"):
        _render_comparison(result, parts)
    else:
        _render_single(result, parts)

    parts.append(
        "<footer><p class='meta'>Generated by AIP Bench</p></footer>"
    )
    parts.append("</body></html>")

    text = "\n".join(parts)
    if path:
        Path(path).write_text(text)
        return None
    return text


# ── Internal helpers ──────────────────────────────────────────

def _esc(text):
    """Escape HTML special characters."""
    return (str(text)
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;"))


def _fmt_val(val):
    """Format a metric value for display."""
    if isinstance(val, float):
        return f"{val:.4f}"
    return _esc(str(val)) if val is not None else "&mdash;"


def _render_comparison(report, parts):
    """Render ComparisonReport tables."""
    for bench_name in report.benchmarks:
        parts.append(f"<h2>{_esc(bench_name)}</h2>")
        parts.append("<table><tr><th>Metric</th>")
        for cfg in report.configs:
            parts.append(f"<th>{_esc(cfg)}</th>")
        parts.append("</tr>")

        all_metrics = set()
        for cfg in report.configs:
            br = report.results[cfg].get(bench_name)
            if br:
                all_metrics.update(br.metrics.keys())

        for metric in sorted(all_metrics):
            parts.append(f"<tr><td><b>{_esc(metric)}</b></td>")
            for cfg in report.configs:
                br = report.results[cfg].get(bench_name)
                val = br.metrics.get(metric) if br else None
                parts.append(f"<td>{_fmt_val(val)}</td>")
            parts.append("</tr>")
        parts.append("</table>")


def _render_single(result, parts):
    """Render a single BenchmarkResult."""
    d = result.to_dict() if hasattr(result, "to_dict") else result
    name = d.get("name", "Benchmark")
    parts.append(f"<h2>{_esc(name)}</h2>")
    parts.append("<table><tr><th>Metric</th><th>Value</th></tr>")
    for metric, value in d.get("metrics", {}).items():
        parts.append(
            f"<tr><td>{_esc(metric)}</td>"
            f"<td>{_fmt_val(value)}</td></tr>"
        )
    parts.append("</table>")

    meta = d.get("metadata")
    if meta:
        parts.append("<h3>Metadata</h3>")
        parts.append("<table><tr><th>Key</th><th>Value</th></tr>")
        for k, v in meta.items():
            parts.append(
                f"<tr><td class='meta'>{_esc(k)}</td>"
                f"<td class='meta'>{_esc(v)}</td></tr>"
            )
        parts.append("</table>")
